import { Chamado } from './types';

export const INITIAL_CHAMADOS: Chamado[] = [
  {
    id: 'ch-101',
    titulo: 'Vazamento de óleo hidráulico no pistão de retorno',
    equipamento: 'Prensa Hidráulica 120T',
    tag_equipamento: 'PR-120-02',
    setor: 'Estamparia Pesada',
    prioridade: 'Alta',
    descricao: 'Durante o ciclo de conformação, foi detectado vazamento intermitente na vedação superior do pistão principal. Nível do reservatório baixando gradativamente.',
    status: 'Aberto',
    operador: 'operador',
    created_at: new Date(Date.now() - 1000 * 60 * 135).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 135).toISOString(),
  },
  {
    id: 'ch-102',
    titulo: 'Ruído excessivo e vibração no cabeçote principal',
    equipamento: 'Torno CNC Mazak 04',
    tag_equipamento: 'CNC-MZ-04',
    setor: 'Usinagem de Precisão',
    prioridade: 'Crítica',
    descricao: 'Acima de 2500 RPM a máquina entra em ressonância com aquecimento anormal no mancal traseiro. Produção pausada por precaução de travamento.',
    status: 'Em Atendimento',
    operador: 'operador',
    mecanico: 'mecanico',
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'ch-100',
    titulo: 'Travamento da esteira de saída de caixas',
    equipamento: 'Esteira Transportadora Linha 03',
    tag_equipamento: 'EST-L03-A',
    setor: 'Embalagem e Expedição',
    prioridade: 'Média',
    descricao: 'Correia patinando sob carga moderada. Sensor de alinhamento indicando desvio lateral de 15mm.',
    status: 'Encerrado',
    operador: 'operador',
    mecanico: 'mecanico',
    solucao: 'Realizado retensionamento do esticador pneumático e substituição do rolete de apoio travado por sujeira residual. Alinhamento a laser conferido e aprovado.',
    pecas_utilizadas: '1x Rolete de Aço Inox 60x400mm, 2x Parafusos M10x35',
    tempo_gasto: '1h 15min',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    closed_at: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
  }
];
